## 1. Download Datasets

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install kaggle -q

In [ ]:
! mkdir ~/.kaggle

In [ ]:
#get keggle API from my gg drive
! cp /content/drive/MyDrive/ProjectSkinCancer/Kaggle_API/kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

### 1.1 Dowload MNIST-HAM10000

In [ ]:
%timeit !kaggle datasets download kmader/skin-cancer-mnist-ham10000

Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
Downloading skin-cancer-mnist-ham10000.zip to /content
100% 5.20G/5.20G [02:40<00:00, 185MB/s]
100% 5.20G/5.20G [02:40<00:00, 34.8MB/s]
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
skin-cancer-mnist-ham10000.zip: Skipping, found more recently modified local copy (use --force to force download)
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
skin-cancer-mnist-ham10000.zip: Skipping, found more recently modified local copy (use --force to force download)
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
User cancelled operation
^C
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
User cancelled operation
^C
^C
^C
Dataset URL: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000
License(s): CC-BY-NC-SA-4.0
^C
The slowest run took 251.96 times longer than the fastest. This could mean that an intermediate result is being cached.
8.41 s ± 11.2 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

### 1.2 Unzip all the download files

In [ ]:
%timeit !unzip skin-cancer-mnist-ham10000.zip

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
  inflating: ham10000_images_part_2/ISIC_0029331.jpg
  inflating: ham10000_images_part_2/ISIC_0029332.jpg
  inflating: ham10000_images_part_2/ISIC_0029333.jpg
  inflating: ham10000_images_part_2/ISIC_0029334.jpg
  inflating: ham10000_images_part_2/ISIC_0029335.jpg
  inflating: ham10000_images_part_2/ISIC_0029336.jpg
  inflating: ham10000_images_part_2/ISIC_0029337.jpg
  inflating: ham10000_images_part_2/ISIC_0029338.jpg
  inflating: ham10000_images_part_2/ISIC_0029339.jpg
  inflating: ham10000_images_part_2/ISIC_0029340.jpg
  inflating: ham10000_images_part_2/ISIC_0029341.jpg
  inflating: ham10000_images_part_2/ISIC_0029342.jpg
  inflating: ham10000_images_part_2/ISIC_0029343.jpg
  inflating: ham10000_images_part_2/ISIC_0029344.jpg
  inflating: ham10000_images_part_2/ISIC_0029345.jpg
  inflating: ham10000_images_part_2/ISIC_0029346.jpg
  inflating: ham10000_images_part_2/ISIC_0029347.jpg
  inflating: ham10000_images_part_2/ISIC_0029348.jpg
  inflating: ham10000_images_part_2/ISIC_0029349.jpg
  inflating: ham10000_images_part_2/ISIC_0029350.jpg
  inflating: ham10000_images_part_2/ISIC_0029351.jpg
  inflating: ham10000_images_part_2/ISIC_0029352.jpg
  inflating: ham10000_images_part_2/ISIC_0029353.jpg
  inflating: ham10000_images_part_2/ISIC_0029354.jpg
  inflating: ham10000_images_part_2/ISIC_0029355.jpg
  inflating: ham10000_images_part_2/ISIC_0029356.jpg
  inflating: ham10000_images_part_2/ISIC_0029357.jpg
  inflating: ham10000_images_part_2/ISIC_0029358.jpg
  inflating: ham10000_images_part_2/ISIC_0029359.jpg
  inflating: ham10000_images_part_2/ISIC_0029360.jpg
  inflating: ham10000_images_part_2/ISIC_0029361.jpg
  inflating: ham10000_images_part_2/ISIC_0029362.jpg
  inflating: ham10000_images_part_2/ISIC_0029363.jpg
  inflating: ham10000_images_part_2/ISIC_0029364.jpg
  inflating: ham10000_images_part_2/ISIC_0029365.jpg
  inflating: ham10000_images_part_2/ISIC_0029366.jpg
  inflating: ham10000_images_part_2/ISIC_0029367.jpg
  inflating: ham10000_images_part_2/ISIC_0029368.jpg
  inflating: ham10000_images_part_2/ISIC_0029369.jpg
  inflating: ham10000_images_part_2/ISIC_0029370.jpg
  inflating: ham10000_images_part_2/ISIC_0029371.jpg
  inflating: ham10000_images_part_2/ISIC_0029372.jpg
  inflating: ham10000_images_part_2/ISIC_0029373.jpg
  inflating: ham10000_images_part_2/ISIC_0029374.jpg
  inflating: ham10000_images_part_2/ISIC_0029375.jpg
  inflating: ham10000_images_part_2/ISIC_0029376.jpg
  inflating: ham10000_images_part_2/ISIC_0029377.jpg
  inflating: ham10000_images_part_2/ISIC_0029378.jpg
  inflating: ham10000_images_part_2/ISIC_0029379.jpg
  inflating: ham10000_images_part_2/ISIC_0029380.jpg
  inflating: ham10000_images_part_2/ISIC_0029381.jpg
  inflating: ham10000_images_part_2/ISIC_0029382.jpg
  inflating: ham10000_images_part_2/ISIC_0029383.jpg
  inflating: ham10000_images_part_2/ISIC_0029384.jpg
  inflating: ham10000_images_part_2/ISIC_0029385.jpg
  inflating: ham10000_images_part_2/ISIC_0029386.jpg
  inflating: ham10000_images_part_2/ISIC_0029387.jpg
  inflating: ham10000_images_part_2/ISIC_0029388.jpg
  inflating: ham10000_images_part_2/ISIC_0029389.jpg
  inflating: ham10000_images_part_2/ISIC_0029390.jpg
  inflating: ham10000_images_part_2/ISIC_0029391.jpg
  inflating: ham10000_images_part_2/ISIC_0029392.jpg
  inflating: ham10000_images_part_2/ISIC_0029393.jpg
  inflating: ham10000_images_part_2/ISIC_0029394.jpg
  inflating: ham10000_images_part_2/ISIC_0029395.jpg
  inflating: ham10000_images_part_2/ISIC_0029396.jpg
  inflating: ham10000_images_part_2/ISIC_0029397.jpg
  inflating: ham10000_images_part_2/ISIC_0029398.jpg
  inflating: ham10000_images_part_2/ISIC_0029399.jpg
  inflating: ham10000_images_part_2/ISIC_0029400.jpg
  inflating: ham10000_images_part_2/ISIC_0029401.jpg
  inflating: ham10000_images_part_2/ISIC_0029402.jpg
  inflating: ham10000_images_part_2/ISIC_0029403.jpg
  inflating: ham10000_images_part_2/ISIC_0029404.jpg
  inflating: ham10000_images_part_2/ISIC_0029405.jpg
  inflating: ham10000_images_part_2/ISIC_0029406.jpg
  inflating: ham10000_images_part_2/ISIC_0029407.jpg
  inflating: ham10000_images_part_2/ISIC_0029408.jpg
  inflating: ham10000_images_part_2/ISIC_0029409.jpg
  inflating: ham10000_images_part_2/ISIC_0029410.jpg
  inflating: ham10000_images_part_2/ISIC_0029411.jpg
  inflating: ham10000_images_part_2/ISIC_0029412.jpg
  inflating: ham10000_images_part_2/ISIC_0029413.jpg
  inflating: ham10000_images_part_2/ISIC_0029414.jpg
  inflating: ham10000_images_part_2/ISIC_0029415.jpg
  inflating: ham10000_images_part_2/ISIC_0029416.jpg
  inflating: ham10000_images_part_2/ISIC_0029417.jpg
  inflating: ham10000_images_part_2/ISIC_0029418.jpg
  inflating: ham10000_images_part_2/ISIC_0029419.jpg
  inflating: ham10000_images_part_2/ISIC_0029420.jpg
  inflating: ham10000_images_part_2/ISIC_0029421.jpg
  inflating: ham10000_images_part_2/ISIC_0029422.jpg
  inflating: ham10000_images_part_2/ISIC_0029423.jpg
  inflating: ham10000_images_part_2/ISIC_0029424.jpg
  inflating: ham10000_images_part_2/ISIC_0029425.jpg
  inflating: ham10000_images_part_2/ISIC_0029426.jpg
  inflating: ham10000_images_part_2/ISIC_0029427.jpg
  inflating: ham10000_images_part_2/ISIC_0029428.jpg
  inflating: ham10000_images_part_2/ISIC_0029429.jpg
  inflating: ham10000_images_part_2/ISIC_0029430.jpg
  inflating: ham10000_images_part_2/ISIC_0029431.jpg
  inflating: ham10000_images_part_2/ISIC_0029432.jpg
  inflating: ham10000_images_part_2/ISIC_0029433.jpg
  inflating: ham10000_images_part_2/ISIC_0029434.jpg
  inflating: ham10000_images_part_2/ISIC_0029435.jpg
  inflating: ham10000_images_part_2/ISIC_0029436.jpg
  inflating: ham10000_images_part_2/ISIC_0029437.jpg
  inflating: ham10000_images_part_2/ISIC_0029438.jpg
  inflating: ham10000_images_part_2/ISIC_0029439.jpg
  inflating: ham10000_images_part_2/ISIC_0029440.jpg
  inflating: ham10000_images_part_2/ISIC_0029441.jpg
  inflating: ham10000_images_part_2/ISIC_0029442.jpg
  inflating: ham10000_images_part_2/ISIC_0029443.jpg
  inflating: ham10000_images_part_2/ISIC_0029444.jpg
  inflating: ham10000_images_part_2/ISIC_0029445.jpg
  inflating: ham10000_images_part_2/ISIC_0029446.jpg
  inflating: ham10000_images_part_2/ISIC_0029447.jpg
  inflating: ham10000_images_part_2/ISIC_0029448.jpg
  inflating: ham10000_images_part_2/ISIC_0029449.jpg
  inflating: ham10000_images_part_2/ISIC_0029450.jpg
  inflating: ham10000_images_part_2/ISIC_0029451.jpg
  inflating: ham10000_images_part_2/ISIC_0029452.jpg
  inflating: ham10000_images_part_2/ISIC_0029453.jpg
  inflating: ham10000_images_part_2/ISIC_0029454.jpg
  inflating: ham10000_images_part_2/ISIC_0029455.jpg
  inflating: ham10000_images_part_2/ISIC_0029456.jpg
  inflating: ham10000_images_part_2/ISIC_0029457.jpg
  inflating: ham10000_images_part_2/ISIC_0029458.jpg
  inflating: ham10000_images_part_2/ISIC_0029459.jpg
  inflating: ham10000_images_part_2/ISIC_0029460.jpg
  inflating: ham10000_images_part_2/ISIC_0029461.jpg
  inflating: ham10000_images_part_2/ISIC_0029462.jpg
  inflating: ham10000_images_part_2/ISIC_0029463.jpg
  inflating: ham10000_images_part_2/ISIC_0029464.jpg
  inflating: ham10000_images_part_2/ISIC_0029465.jpg
  inflating: ham10000_images_part_2/ISIC_0029466.jpg
  inflating: ham10000_images_part_2/ISIC_0029467.jpg
  inflating: ham10000_images_part_2/ISIC_0029468.jpg
  inflating: ham10000_images_part_2/ISIC_0029469.jpg
  inflating: ham10000_images_part_2/ISIC_0029470.jpg
  inflating: ham10000_images_part_2/ISIC_0029471.jpg
  inflating: ham10000_images_part_2/ISIC_0029472.jpg
  inflating: ham10000_images_part_2/ISIC_0029473.jpg
  inflating: ham10000_images_part_2/ISIC_0029474.jpg
  inflating: ham10000_images_part_2/ISIC_0029475.jpg
  inflating: ham10000_images_part_2/ISIC_0029476.jpg
  inflating: ham10000_images_part_2/ISIC_0029477.jpg
  inflating: ham10000_images_part_2/ISIC_0029478.jpg
  inflating: ham10000_images_part_2/ISIC_0029479.jpg
  inflating: ham10000_images_part_2/ISIC_0029480.jpg
  inflating: ham10000_images_part_2/ISIC_0029481.jpg
  inflating: ham10000_images_part_2/ISIC_0029482.jpg
  inflating: ham10000_images_part_2/ISIC_0029483.jpg
  inflating: ham10000_images_part_2/ISIC_0029484.jpg
  inflating: ham10000_images_part_2/ISIC_0029485.jpg
  inflating: ham10000_images_part_2/ISIC_0029486.jpg
  inflating: ham10000_images_part_2/ISIC_0029487.jpg
  inflating: ham10000_images_part_2/ISIC_0029488.jpg
  inflating: ham10000_images_part_2/ISIC_0029489.jpg
  inflating: ham10000_images_part_2/ISIC_0029490.jpg
  inflating: ham10000_images_part_2/ISIC_0029491.jpg
  inflating: ham10000_images_part_2/ISIC_0029492.jpg
  inflating: ham10000_images_part_2/ISIC_0029493.jpg
  inflating: ham10000_images_part_2/ISIC_0029494.jpg
  inflating: ham10000_images_part_2/ISIC_0029495.jpg
  inflating: ham10000_images_part_2/ISIC_0029496.jpg
  inflating: ham10000_images_part_2/ISIC_0029497.jpg
  inflating: ham10000_images_part_2/ISIC_0029498.jpg
  inflating: ham10000_images_part_2/ISIC_0029499.jpg
  inflating: ham10000_images_part_2/ISIC_0029500.jpg
  inflating: ham10000_images_part_2/ISIC_0029501.jpg
  inflating: ham10000_images_part_2/ISIC_0029502.jpg
  inflating: ham10000_images_part_2/ISIC_0029503.jpg
  inflating: ham10000_images_part_2/ISIC_0029504.jpg
  inflating: ham10000_images_part_2/ISIC_0029505.jpg
  inflating: ham10000_images_part_2/ISIC_0029506.jpg
  inflating: ham10000_images_part_2/ISIC_0029507.jpg
  inflating: ham10000_images_part_2/ISIC_0029508.jpg
  inflating: ham10000_images_part_2/ISIC_0029509.jpg
  inflating: ham10000_images_part_2/ISIC_0029510.jpg
  inflating: ham10000_images_part_2/ISIC_0029511.jpg
  inflating: ham10000_images_part_2/ISIC_0029512.jpg
  inflating: ham10000_images_part_2/ISIC_0029513.jpg
  inflating: ham10000_images_part_2/ISIC_0029514.jpg
  inflating: ham10000_images_part_2/ISIC_0029515.jpg
  inflating: ham10000_images_part_2/ISIC_0029516.jpg
  inflating: ham10000_images_part_2/ISIC_0029517.jpg
  inflating: ham10000_images_part_2/ISIC_0029518.jpg
  inflating: ham10000_images_part_2/ISIC_0029519.jpg
  inflating: ham10000_images_part_2/ISIC_0029520.jpg
  inflating: ham10000_images_part_2/ISIC_0029521.jpg
  inflating: ham10000_images_part_2/ISIC_0029522.jpg
  inflating: ham10000_images_part_2/ISIC_0029523.jpg
  inflating: ham10000_images_part_2/ISIC_0029524.jpg
  inflating: ham10000_images_part_2/ISIC_0029525.jpg
  inflating: ham10000_images_part_2/ISIC_0029526.jpg
  inflating: ham10000_images_part_2/ISIC_0029527.jpg
  inflating: ham10000_images_part_2/ISIC_0029528.jpg
  inflating: ham10000_images_part_2/ISIC_0029529.jpg
  inflating: ham10000_images_part_2/ISIC_0029530.jpg
  inflating: ham10000_images_part_2/ISIC_0029531.jpg
  inflating: ham10000_images_part_2/ISIC_0029532.jpg
  inflating: ham10000_images_part_2/ISIC_0029533.jpg
  inflating: ham10000_images_part_2/ISIC_0029534.jpg
  inflating: ham10000_images_part_2/ISIC_0029535.jpg
  inflating: ham10000_images_part_2/ISIC_0029536.jpg
  inflating: ham10000_images_part_2/ISIC_0029537.jpg
  inflating: ham10000_images_part_2/ISIC_0029538.jpg
  inflating: ham10000_images_part_2/ISIC_0029539.jpg
  inflating: ham10000_images_part_2/ISIC_0029540.jpg
  inflating: ham10000_images_part_2/ISIC_0029541.jpg
  inflating: ham10000_images_part_2/ISIC_0029542.jpg
  inflating: ham10000_images_part_2/ISIC_0029543.jpg
  inflating: ham10000_images_part_2/ISIC_0029544.jpg
  inflating: ham10000_images_part_2/ISIC_0029545.jpg
  inflating: ham10000_images_part_2/ISIC_0029546.jpg
  inflating: ham10000_images_part_2/ISIC_0029547.jpg
  inflating: ham10000_images_part_2/ISIC_0029548.jpg
  inflating: ham10000_images_part_2/ISIC_0029549.jpg
  inflating: ham10000_images_part_2/ISIC_0029550.jpg
  inflating: ham10000_images_part_2/ISIC_0029551.jpg
  inflating: ham10000_images_part_2/ISIC_0029552.jpg
  inflating: ham10000_images_part_2/ISIC_0029553.jpg
  inflating: ham10000_images_part_2/ISIC_0029554.jpg
  inflating: ham10000_images_part_2/ISIC_0029555.jpg
  inflating: ham10000_images_part_2/ISIC_0029556.jpg
  inflating: ham10000_images_part_2/ISIC_0029557.jpg
  inflating: ham10000_images_part_2/ISIC_0029558.jpg
  inflating: ham10000_images_part_2/ISIC_0029559.jpg
  inflating: ham10000_images_part_2/ISIC_0029560.jpg
  inflating: ham10000_images_part_2/ISIC_0029561.jpg
  inflating: ham10000_images_part_2/ISIC_0029562.jpg
  inflating: ham10000_images_part_2/ISIC_0029563.jpg
  inflating: ham10000_images_part_2/ISIC_0029564.jpg
  inflating: ham10000_images_part_2/ISIC_0029565.jpg
  inflating: ham10000_images_part_2/ISIC_0029566.jpg
  inflating: ham10000_images_part_2/ISIC_0029567.jpg
  inflating: ham10000_images_part_2/ISIC_0029568.jpg
  inflating: ham10000_images_part_2/ISIC_0029569.jpg
  inflating: ham10000_images_part_2/ISIC_0029570.jpg
  inflating: ham10000_images_part_2/ISIC_0029571.jpg
  inflating: ham10000_images_part_2/ISIC_0029572.jpg
  inflating: ham10000_images_part_2/ISIC_0029573.jpg
  inflating: ham10000_images_part_2/ISIC_0029574.jpg
  inflating: ham10000_images_part_2/ISIC_0029575.jpg
  inflating: ham10000_images_part_2/ISIC_0029576.jpg
  inflating: ham10000_images_part_2/ISIC_0029577.jpg
  inflating: ham10000_images_part_2/ISIC_0029578.jpg
  inflating: ham10000_images_part_2/ISIC_0029579.jpg
  inflating: ham10000_images_part_2/ISIC_0029580.jpg
  inflating: ham10000_images_part_2/ISIC_0029581.jpg
  inflating: ham10000_images_part_2/ISIC_0029582.jpg
  inflating: ham10000_images_part_2/ISIC_0029583.jpg
  inflating: ham10000_images_part_2/ISIC_0029584.jpg
  inflating: ham10000_images_part_2/ISIC_0029585.jpg
  inflating: ham10000_images_part_2/ISIC_0029586.jpg
  inflating: ham10000_images_part_2/ISIC_0029587.jpg
  inflating: ham10000_images_part_2/ISIC_0029588.jpg
  inflating: ham10000_images_part_2/ISIC_0029589.jpg
  inflating: ham10000_images_part_2/ISIC_0029590.jpg
  inflating: ham10000_images_part_2/ISIC_0029591.jpg
  inflating: ham10000_images_part_2/ISIC_0029592.jpg
  inflating: ham10000_images_part_2/ISIC_0029593.jpg
  inflating: ham10000_images_part_2/ISIC_0029594.jpg
  inflating: ham10000_images_part_2/ISIC_0029595.jpg
  inflating: ham10000_images_part_2/ISIC_0029596.jpg
  inflating: ham10000_images_part_2/ISIC_0029597.jpg
  inflating: ham10000_images_part_2/ISIC_0029598.jpg
  inflating: ham10000_images_part_2/ISIC_0029599.jpg
  inflating: ham10000_images_part_2/ISIC_0029600.jpg
  inflating: ham10000_images_part_2/ISIC_0029601.jpg
  inflating: ham10000_images_part_2/ISIC_0029602.jpg
  inflating: ham10000_images_part_2/ISIC_0029603.jpg
  inflating: ham10000_images_part_2/ISIC_0029604.jpg
  inflating: ham10000_images_part_2/ISIC_0029605.jpg
  inflating: ham10000_images_part_2/ISIC_0029606.jpg
  inflating: ham10000_images_part_2/ISIC_0029607.jpg
  inflating: ham10000_images_part_2/ISIC_0029608.jpg
  inflating: ham10000_images_part_2/ISIC_0029609.jpg
  inflating: ham10000_images_part_2/ISIC_0029610.jpg
  inflating: ham10000_images_part_2/ISIC_0029611.jpg
  inflating: ham10000_images_part_2/ISIC_0029612.jpg
  inflating: ham10000_images_part_2/ISIC_0029613.jpg
  inflating: ham10000_images_part_2/ISIC_0029614.jpg
  inflating: ham10000_images_part_2/ISIC_0029615.jpg
  inflating: ham10000_images_part_2/ISIC_0029616.jpg
  inflating: ham10000_images_part_2/ISIC_0029617.jpg
  inflating: ham10000_images_part_2/ISIC_0029618.jpg
  inflating: ham10000_images_part_2/ISIC_0029619.jpg
  inflating: ham10000_images_part_2/ISIC_0029620.jpg
  inflating: ham10000_images_part_2/ISIC_0029621.jpg
  inflating: ham10000_images_part_2/ISIC_0029622.jpg
  inflating: ham10000_images_part_2/ISIC_0029623.jpg
  inflating: ham10000_images_part_2/ISIC_0029624.jpg
  inflating: ham10000_images_part_2/ISIC_0029625.jpg
  inflating: ham10000_images_part_2/ISIC_0029626.jpg
  inflating: ham10000_images_part_2/ISIC_0029627.jpg
  inflating: ham10000_images_part_2/ISIC_0029628.jpg
  inflating: ham10000_images_part_2/ISIC_0029629.jpg
  inflating: ham10000_images_part_2/ISIC_0029630.jpg
  inflating: ham10000_images_part_2/ISIC_0029631.jpg
  inflating: ham10000_images_part_2/ISIC_0029632.jpg
  inflating: ham10000_images_part_2/ISIC_0029633.jpg
  inflating: ham10000_images_part_2/ISIC_0029634.jpg
  inflating: ham10000_images_part_2/ISIC_0029635.jpg
  inflating: ham10000_images_part_2/ISIC_0029636.jpg
  inflating: ham10000_images_part_2/ISIC_0029637.jpg
  inflating: ham10000_images_part_2/ISIC_0029638.jpg
  inflating: ham10000_images_part_2/ISIC_0029639.jpg
  inflating: ham10000_images_part_2/ISIC_0029640.jpg
  inflating: ham10000_images_part_2/ISIC_0029641.jpg
  inflating: ham10000_images_part_2/ISIC_0029642.jpg
  inflating: ham10000_images_part_2/ISIC_0029643.jpg
  inflating: ham10000_images_part_2/ISIC_0029644.jpg
  inflating: ham10000_images_part_2/ISIC_0029645.jpg
  inflating: ham10000_images_part_2/ISIC_0029646.jpg
  inflating: ham10000_images_part_2/ISIC_0029647.jpg
  inflating: ham10000_images_part_2/ISIC_0029648.jpg
  inflating: ham10000_images_part_2/ISIC_0029649.jpg
  inflating: ham10000_images_part_2/ISIC_0029650.jpg
  inflating: ham10000_images_part_2/ISIC_0029651.jpg
  inflating: ham10000_images_part_2/ISIC_0029652.jpg
  inflating: ham10000_images_part_2/ISIC_0029653.jpg
  inflating: ham10000_images_part_2/ISIC_0029654.jpg
  inflating: ham10000_images_part_2/ISIC_0029655.jpg
  inflating: ham10000_images_part_2/ISIC_0029656.jpg
  inflating: ham10000_images_part_2/ISIC_0029657.jpg
  inflating: ham10000_images_part_2/ISIC_0029658.jpg
  inflating: ham10000_images_part_2/ISIC_0029659.jpg
  inflating: ham10000_images_part_2/ISIC_0029660.jpg
  inflating: ham10000_images_part_2/ISIC_0029661.jpg
  inflating: ham10000_images_part_2/ISIC_0029662.jpg
  inflating: ham10000_images_part_2/ISIC_0029663.jpg
  inflating: ham10000_images_part_2/ISIC_0029664.jpg
  inflating: ham10000_images_part_2/ISIC_0029665.jpg
  inflating: ham10000_images_part_2/ISIC_0029666.jpg
  inflating: ham10000_images_part_2/ISIC_0029667.jpg
  inflating: ham10000_images_part_2/ISIC_0029668.jpg
  inflating: ham10000_images_part_2/ISIC_0029669.jpg
  inflating: ham10000_images_part_2/ISIC_0029670.jpg
  inflating: ham10000_images_part_2/ISIC_0029671.jpg
  inflating: ham10000_images_part_2/ISIC_0029672.jpg
  inflating: ham10000_images_part_2/ISIC_0029673.jpg
  inflating: ham10000_images_part_2/ISIC_0029674.jpg
  inflating: ham10000_images_part_2/ISIC_0029675.jpg
  inflating: ham10000_images_part_2/ISIC_0029676.jpg
  inflating: ham10000_images_part_2/ISIC_0029677.jpg
  inflating: ham10000_images_part_2/ISIC_0029678.jpg
  inflating: ham10000_images_part_2/ISIC_0029679.jpg
  inflating: ham10000_images_part_2/ISIC_0029680.jpg
  inflating: ham10000_images_part_2/ISIC_0029681.jpg
  inflating: ham10000_images_part_2/ISIC_0029682.jpg
  inflating: ham10000_images_part_2/ISIC_0029683.jpg
  inflating: ham10000_images_part_2/ISIC_0029684.jpg
  inflating: ham10000_images_part_2/ISIC_0029685.jpg
  inflating: ham10000_images_part_2/ISIC_0029686.jpg
  inflating: ham10000_images_part_2/ISIC_0029687.jpg
  inflating: ham10000_images_part_2/ISIC_0029688.jpg
  inflating: ham10000_images_part_2/ISIC_0029689.jpg
  inflating: ham10000_images_part_2/ISIC_0029690.jpg
  inflating: ham10000_images_part_2/ISIC_0029691.jpg
  inflating: ham10000_images_part_2/ISIC_0029692.jpg
  inflating: ham10000_images_part_2/ISIC_0029693.jpg
  inflating: ham10000_images_part_2/ISIC_0029694.jpg
  inflating: ham10000_images_part_2/ISIC_0029695.jpg
  inflating: ham10000_images_part_2/ISIC_0029696.jpg
  inflating: ham10000_images_part_2/ISIC_0029697.jpg
  inflating: ham10000_images_part_2/ISIC_0029698.jpg
  inflating: ham10000_images_part_2/ISIC_0029699.jpg
  inflating: ham10000_images_part_2/ISIC_0029700.jpg
  inflating: ham10000_images_part_2/ISIC_0029701.jpg
  inflating: ham10000_images_part_2/ISIC_0029702.jpg
  inflating: ham10000_images_part_2/ISIC_0029703.jpg
  inflating: ham10000_images_part_2/ISIC_0029704.jpg
  inflating: ham10000_images_part_2/ISIC_0029705.jpg
  inflating: ham10000_images_part_2/ISIC_0029706.jpg

In [ ]:
%timeit ! unzip /content/drive/MyDrive/All_BCN20000/BCN_20k_train.zip

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
  inflating: bcn_20k_train/BCN_0000012248.jpg
  inflating: bcn_20k_train/BCN_0000012250.jpg
  inflating: bcn_20k_train/BCN_0000012251.jpg
  inflating: bcn_20k_train/BCN_0000012252.jpg
  inflating: bcn_20k_train/BCN_0000012254.jpg
  inflating: bcn_20k_train/BCN_0000012256.jpg
  inflating: bcn_20k_train/BCN_0000012257.jpg
  inflating: bcn_20k_train/BCN_0000012258.jpg
  inflating: bcn_20k_train/BCN_0000012259.jpg
  inflating: bcn_20k_train/BCN_0000012260.jpg
  inflating: bcn_20k_train/BCN_0000012262.jpg
  inflating: bcn_20k_train/BCN_0000012263.jpg
  inflating: bcn_20k_train/BCN_0000012264.jpg
  inflating: bcn_20k_train/BCN_0000012265.jpg
  inflating: bcn_20k_train/BCN_0000012268.jpg
  inflating: bcn_20k_train/BCN_0000012270.jpg
  inflating: bcn_20k_train/BCN_0000012271.jpg
  inflating: bcn_20k_train/BCN_0000012272.jpg
  inflating: bcn_20k_train/BCN_0000012273.jpg
  inflating: bcn_20k_train/BCN_0000012274.jpg
  inflating: bcn_20k_train/BCN_0000012275.jpg
  inflating: bcn_20k_train/BCN_0000012277.jpg
  inflating: bcn_20k_train/BCN_0000012278.jpg
  inflating: bcn_20k_train/BCN_0000012279.jpg
  inflating: bcn_20k_train/BCN_0000012280.jpg
  inflating: bcn_20k_train/BCN_0000012281.jpg
  inflating: bcn_20k_train/BCN_0000012282.jpg
  inflating: bcn_20k_train/BCN_0000012284.jpg
  inflating: bcn_20k_train/BCN_0000012285.jpg
  inflating: bcn_20k_train/BCN_0000012286.jpg
  inflating: bcn_20k_train/BCN_0000012287.jpg
  inflating: bcn_20k_train/BCN_0000012288.jpg
  inflating: bcn_20k_train/BCN_0000012293.jpg
  inflating: bcn_20k_train/BCN_0000012294.jpg
  inflating: bcn_20k_train/BCN_0000012296.jpg
  inflating: bcn_20k_train/BCN_0000012297.jpg
  inflating: bcn_20k_train/BCN_0000012298.jpg
  inflating: bcn_20k_train/BCN_0000012301.jpg
  inflating: bcn_20k_train/BCN_0000012302.jpg
  inflating: bcn_20k_train/BCN_0000012303.jpg
  inflating: bcn_20k_train/BCN_0000012308.jpg
  inflating: bcn_20k_train/BCN_0000012309.jpg
  inflating: bcn_20k_train/BCN_0000012310.jpg
  inflating: bcn_20k_train/BCN_0000012311.jpg
  inflating: bcn_20k_train/BCN_0000012312.jpg
  inflating: bcn_20k_train/BCN_0000012313.jpg
  inflating: bcn_20k_train/BCN_0000012314.jpg
  inflating: bcn_20k_train/BCN_0000012315.jpg
  inflating: bcn_20k_train/BCN_0000012318.jpg
  inflating: bcn_20k_train/BCN_0000012321.jpg
  inflating: bcn_20k_train/BCN_0000012322.jpg
  inflating: bcn_20k_train/BCN_0000012323.jpg
  inflating: bcn_20k_train/BCN_0000012329.jpg
  inflating: bcn_20k_train/BCN_0000012330.jpg
  inflating: bcn_20k_train/BCN_0000012331.jpg
  inflating: bcn_20k_train/BCN_0000012332.jpg
  inflating: bcn_20k_train/BCN_0000012335.jpg
  inflating: bcn_20k_train/BCN_0000012337.jpg
  inflating: bcn_20k_train/BCN_0000012339.jpg
  inflating: bcn_20k_train/BCN_0000012340.jpg
  inflating: bcn_20k_train/BCN_0000012343.jpg
  inflating: bcn_20k_train/BCN_0000012344.jpg
  inflating: bcn_20k_train/BCN_0000012345.jpg
  inflating: bcn_20k_train/BCN_0000012347.jpg
  inflating: bcn_20k_train/BCN_0000012349.jpg
  inflating: bcn_20k_train/BCN_0000012350.jpg
  inflating: bcn_20k_train/BCN_0000012351.jpg
  inflating: bcn_20k_train/BCN_0000012352.jpg
  inflating: bcn_20k_train/BCN_0000012353.jpg
  inflating: bcn_20k_train/BCN_0000012354.jpg
  inflating: bcn_20k_train/BCN_0000012355.jpg
  inflating: bcn_20k_train/BCN_0000012358.jpg
  inflating: bcn_20k_train/BCN_0000012359.jpg
  inflating: bcn_20k_train/BCN_0000012362.jpg
  inflating: bcn_20k_train/BCN_0000012363.jpg
  inflating: bcn_20k_train/BCN_0000012365.jpg
  inflating: bcn_20k_train/BCN_0000012366.jpg
  inflating: bcn_20k_train/BCN_0000012368.jpg
  inflating: bcn_20k_train/BCN_0000012371.jpg
  inflating: bcn_20k_train/BCN_0000012372.jpg
  inflating: bcn_20k_train/BCN_0000012373.jpg
  inflating: bcn_20k_train/BCN_0000012374.jpg
  inflating: bcn_20k_train/BCN_0000012375.jpg
  inflating: bcn_20k_train/BCN_0000012377.jpg
  inflating: bcn_20k_train/BCN_0000012381.jpg
  inflating: bcn_20k_train/BCN_0000012384.jpg
  inflating: bcn_20k_train/BCN_0000012385.jpg
  inflating: bcn_20k_train/BCN_0000012386.jpg
  inflating: bcn_20k_train/BCN_0000012388.jpg
  inflating: bcn_20k_train/BCN_0000012389.jpg
  inflating: bcn_20k_train/BCN_0000012391.jpg
  inflating: bcn_20k_train/BCN_0000012392.jpg
  inflating: bcn_20k_train/BCN_0000012393.jpg
  inflating: bcn_20k_train/BCN_0000012396.jpg
  inflating: bcn_20k_train/BCN_0000012397.jpg
  inflating: bcn_20k_train/BCN_0000012399.jpg
  inflating: bcn_20k_train/BCN_0000012400.jpg
  inflating: bcn_20k_train/BCN_0000012401.jpg
  inflating: bcn_20k_train/BCN_0000012402.jpg
  inflating: bcn_20k_train/BCN_0000012404.jpg
  inflating: bcn_20k_train/BCN_0000012406.jpg
  inflating: bcn_20k_train/BCN_0000012408.jpg
  inflating: bcn_20k_train/BCN_0000012411.jpg
  inflating: bcn_20k_train/BCN_0000012412.jpg
  inflating: bcn_20k_train/BCN_0000012415.jpg
  inflating: bcn_20k_train/BCN_0000012417.jpg
  inflating: bcn_20k_train/BCN_0000012418.jpg
  inflating: bcn_20k_train/BCN_0000012419.jpg
  inflating: bcn_20k_train/BCN_0000012420.jpg
  inflating: bcn_20k_train/BCN_0000012421.jpg
  inflating: bcn_20k_train/BCN_0000012422.jpg
  inflating: bcn_20k_train/BCN_0000012423.jpg
  inflating: bcn_20k_train/BCN_0000012424.jpg
  inflating: bcn_20k_train/BCN_0000012425.jpg
  inflating: bcn_20k_train/BCN_0000012428.jpg
  inflating: bcn_20k_train/BCN_0000012430.jpg
  inflating: bcn_20k_train/BCN_0000012431.jpg
  inflating: bcn_20k_train/BCN_0000012432.jpg
  inflating: bcn_20k_train/BCN_0000012433.jpg
  inflating: bcn_20k_train/BCN_0000012434.jpg
  inflating: bcn_20k_train/BCN_0000012436.jpg
  inflating: bcn_20k_train/BCN_0000012438.jpg
  inflating: bcn_20k_train/BCN_0000012439.jpg
  inflating: bcn_20k_train/BCN_0000012440.jpg
  inflating: bcn_20k_train/BCN_0000012442.jpg
  inflating: bcn_20k_train/BCN_0000012445.jpg
  inflating: bcn_20k_train/BCN_0000012447.jpg
  inflating: bcn_20k_train/BCN_0000012449.jpg
  inflating: bcn_20k_train/BCN_0000012451.jpg
  inflating: bcn_20k_train/BCN_0000012453.jpg
  inflating: bcn_20k_train/BCN_0000012454.jpg
  inflating: bcn_20k_train/BCN_0000012457.jpg
  inflating: bcn_20k_train/BCN_0000012462.jpg
  inflating: bcn_20k_train/BCN_0000012463.jpg
  inflating: bcn_20k_train/BCN_0000012464.jpg
  inflating: bcn_20k_train/BCN_0000012465.jpg
  inflating: bcn_20k_train/BCN_0000012466.jpg
  inflating: bcn_20k_train/BCN_0000012467.jpg
  inflating: bcn_20k_train/BCN_0000012469.jpg
  inflating: bcn_20k_train/BCN_0000012470.jpg
  inflating: bcn_20k_train/BCN_0000012471.jpg
  inflating: bcn_20k_train/BCN_0000012472.jpg
  inflating: bcn_20k_train/BCN_0000012473.jpg
  inflating: bcn_20k_train/BCN_0000012474.jpg
  inflating: bcn_20k_train/BCN_0000012475.jpg
  inflating: bcn_20k_train/BCN_0000012476.jpg
  inflating: bcn_20k_train/BCN_0000012477.jpg
  inflating: bcn_20k_train/BCN_0000012478.jpg
  inflating: bcn_20k_train/BCN_0000012479.jpg
  inflating: bcn_20k_train/BCN_0000012480.jpg
  inflating: bcn_20k_train/BCN_0000012482.jpg
  inflating: bcn_20k_train/BCN_0000012483.jpg
  inflating: bcn_20k_train/BCN_0000012485.jpg
  inflating: bcn_20k_train/BCN_0000012486.jpg
  inflating: bcn_20k_train/BCN_0000012487.jpg
  inflating: bcn_20k_train/BCN_0000012488.jpg
  inflating: bcn_20k_train/BCN_0000012489.jpg
  inflating: bcn_20k_train/BCN_0000012490.jpg
  inflating: bcn_20k_train/BCN_0000012492.jpg
  inflating: bcn_20k_train/BCN_0000012496.jpg
  inflating: bcn_20k_train/BCN_0000012497.jpg
  inflating: bcn_20k_train/BCN_0000012498.jpg
  inflating: bcn_20k_train/BCN_0000012500.jpg
  inflating: bcn_20k_train/BCN_0000012501.jpg
  inflating: bcn_20k_train/BCN_0000012502.jpg
  inflating: bcn_20k_train/BCN_0000012505.jpg
  inflating: bcn_20k_train/BCN_0000012508.jpg
  inflating: bcn_20k_train/BCN_0000012509.jpg
  inflating: bcn_20k_train/BCN_0000012510.jpg
  inflating: bcn_20k_train/BCN_0000012512.jpg
  inflating: bcn_20k_train/BCN_0000012513.jpg
  inflating: bcn_20k_train/BCN_0000012514.jpg
  inflating: bcn_20k_train/BCN_0000012515.jpg
  inflating: bcn_20k_train/BCN_0000012516.jpg
  inflating: bcn_20k_train/BCN_0000012517.jpg
  inflating: bcn_20k_train/BCN_0000012518.jpg
  inflating: bcn_20k_train/BCN_0000012519.jpg
  inflating: bcn_20k_train/BCN_0000012521.jpg
  inflating: bcn_20k_train/BCN_0000012522.jpg
  inflating: bcn_20k_train/BCN_0000012523.jpg
  inflating: bcn_20k_train/BCN_0000012525.jpg
  inflating: bcn_20k_train/BCN_0000012526.jpg
  inflating: bcn_20k_train/BCN_0000012530.jpg
  inflating: bcn_20k_train/BCN_0000012531.jpg
  inflating: bcn_20k_train/BCN_0000012533.jpg
  inflating: bcn_20k_train/BCN_0000012534.jpg
  inflating: bcn_20k_train/BCN_0000012535.jpg
  inflating: bcn_20k_train/BCN_0000012540.jpg
  inflating: bcn_20k_train/BCN_0000012541.jpg
  inflating: bcn_20k_train/BCN_0000012543.jpg
  inflating: bcn_20k_train/BCN_0000012544.jpg
  inflating: bcn_20k_train/BCN_0000012547.jpg
  inflating: bcn_20k_train/BCN_0000012548.jpg
  inflating: bcn_20k_train/BCN_0000012550.jpg
  inflating: bcn_20k_train/BCN_0000012551.jpg
  inflating: bcn_20k_train/BCN_0000012552.jpg
  inflating: bcn_20k_train/BCN_0000012554.jpg
  inflating: bcn_20k_train/BCN_0000012556.jpg
  inflating: bcn_20k_train/BCN_0000012557.jpg
  inflating: bcn_20k_train/BCN_0000012558.jpg
  inflating: bcn_20k_train/BCN_0000012561.jpg
  inflating: bcn_20k_train/BCN_0000012563.jpg
  inflating: bcn_20k_train/BCN_0000012564.jpg
  inflating: bcn_20k_train/BCN_0000012567.jpg
  inflating: bcn_20k_train/BCN_0000012570.jpg
  inflating: bcn_20k_train/BCN_0000012573.jpg
  inflating: bcn_20k_train/BCN_0000012574.jpg
  inflating: bcn_20k_train/BCN_0000012575.jpg
  inflating: bcn_20k_train/BCN_0000012577.jpg
  inflating: bcn_20k_train/BCN_0000012578.jpg
  inflating: bcn_20k_train/BCN_0000012580.jpg
  inflating: bcn_20k_train/BCN_0000012582.jpg
  inflating: bcn_20k_train/BCN_0000012583.jpg
  inflating: bcn_20k_train/BCN_0000012585.jpg
  inflating: bcn_20k_train/BCN_0000012586.jpg
  inflating: bcn_20k_train/BCN_0000012587.jpg
  inflating: bcn_20k_train/BCN_0000012589.jpg
  inflating: bcn_20k_train/BCN_0000012595.jpg
  inflating: bcn_20k_train/BCN_0000012597.jpg
  inflating: bcn_20k_train/BCN_0000012600.jpg
  inflating: bcn_20k_train/BCN_0000012601.jpg
  inflating: bcn_20k_train/BCN_0000012605.jpg
  inflating: bcn_20k_train/BCN_0000012607.jpg
  inflating: bcn_20k_train/BCN_0000012608.jpg
  inflating: bcn_20k_train/BCN_0000012609.jpg
  inflating: bcn_20k_train/BCN_0000012610.jpg
  inflating: bcn_20k_train/BCN_0000012611.jpg
  inflating: bcn_20k_train/BCN_0000012612.jpg
  inflating: bcn_20k_train/BCN_0000012614.jpg
  inflating: bcn_20k_train/BCN_0000012615.jpg
  inflating: bcn_20k_train/BCN_0000012619.jpg
  inflating: bcn_20k_train/BCN_0000012622.jpg
  inflating: bcn_20k_train/BCN_0000012626.jpg
  inflating: bcn_20k_train/BCN_0000012627.jpg
  inflating: bcn_20k_train/BCN_0000012629.jpg
  inflating: bcn_20k_train/BCN_0000012630.jpg
  inflating: bcn_20k_train/BCN_0000012631.jpg
  inflating: bcn_20k_train/BCN_0000012632.jpg
  inflating: bcn_20k_train/BCN_0000012635.jpg
  inflating: bcn_20k_train/BCN_0000012636.jpg
  inflating: bcn_20k_train/BCN_0000012637.jpg
  inflating: bcn_20k_train/BCN_0000012640.jpg
  inflating: bcn_20k_train/BCN_0000012641.jpg
  inflating: bcn_20k_train/BCN_0000012642.jpg
  inflating: bcn_20k_train/BCN_0000012643.jpg
  inflating: bcn_20k_train/BCN_0000012646.jpg
  inflating: bcn_20k_train/BCN_0000012647.jpg
  inflating: bcn_20k_train/BCN_0000012648.jpg
  inflating: bcn_20k_train/BCN_0000012654.jpg
  inflating: bcn_20k_train/BCN_0000012655.jpg
  inflating: bcn_20k_train/BCN_0000012656.jpg
  inflating: bcn_20k_train/BCN_0000012657.jpg
  inflating: bcn_20k_train/BCN_0000012658.jpg
  inflating: bcn_20k_train/BCN_0000012661.jpg
  inflating: bcn_20k_train/BCN_0000012662.jpg
  inflating: bcn_20k_train/BCN_0000012663.jpg
  inflating: bcn_20k_train/BCN_0000012664.jpg
  inflating: bcn_20k_train/BCN_0000012665.jpg
  inflating: bcn_20k_train/BCN_0000012668.jpg
  inflating: bcn_20k_train/BCN_0000012669.jpg
  inflating: bcn_20k_train/BCN_0000012670.jpg
  inflating: bcn_20k_train/BCN_0000012673.jpg
  inflating: bcn_20k_train/BCN_0000012674.jpg
  inflating: bcn_20k_train/BCN_0000012675.jpg
  inflating: bcn_20k_train/BCN_0000012680.jpg
  inflating: bcn_20k_train/BCN_0000012681.jpg
  inflating: bcn_20k_train/BCN_0000012682.jpg
  inflating: bcn_20k_train/BCN_0000012683.jpg
  inflating: bcn_20k_train/BCN_0000012685.jpg
  inflating: bcn_20k_train/BCN_0000012686.jpg
  inflating: bcn_20k_train/BCN_0000012687.jpg
  inflating: bcn_20k_train/BCN_0000012688.jpg
  inflating: bcn_20k_train/BCN_0000012691.jpg
  inflating: bcn_20k_train/BCN_0000012692.jpg
  inflating: bcn_20k_train/BCN_0000012695.jpg
  inflating: bcn_20k_train/BCN_0000012696.jpg
  inflating: bcn_20k_train/BCN_0000012697.jpg
  inflating: bcn_20k_train/BCN_0000012698.jpg
  inflating: bcn_20k_train/BCN_0000012699.jpg
  inflating: bcn_20k_train/BCN_0000012700.jpg
  inflating: bcn_20k_train/BCN_0000012701.jpg
  inflating: bcn_20k_train/BCN_0000012702.jpg
  inflating: bcn_20k_train/BCN_0000012703.jpg
  inflating: bcn_20k_train/BCN_0000012704.jpg
  inflating: bcn_20k_train/BCN_0000012707.jpg
  inflating: bcn_20k_train/BCN_0000012709.jpg
  inflating: bcn_20k_train/BCN_0000012710.jpg
  inflating: bcn_20k_train/BCN_0000012711.jpg
  inflating: bcn_20k_train/BCN_0000012712.jpg
  inflating: bcn_20k_train/BCN_0000012714.jpg
  inflating: bcn_20k_train/BCN_0000012717.jpg
  inflating: bcn_20k_train/BCN_0000012719.jpg
  inflating: bcn_20k_train/BCN_0000012721.jpg
  inflating: bcn_20k_train/BCN_0000012723.jpg
  inflating: bcn_20k_train/BCN_0000012724.jpg
  inflating: bcn_20k_train/BCN_0000012726.jpg
  inflating: bcn_20k_train/BCN_0000012728.jpg
  inflating: bcn_20k_train/BCN_0000012729.jpg
  inflating: bcn_20k_train/BCN_0000012730.jpg
  inflating: bcn_20k_train/BCN_0000012734.jpg
  inflating: bcn_20k_train/BCN_0000012735.jpg
  inflating: bcn_20k_train/BCN_0000012736.jpg
  inflating: bcn_20k_train/BCN_0000012738.jpg
  inflating: bcn_20k_train/BCN_0000012739.jpg
  inflating: bcn_20k_train/BCN_0000012740.jpg
  inflating: bcn_20k_train/BCN_0000012741.jpg
  inflating: bcn_20k_train/BCN_0000012742.jpg
  inflating: bcn_20k_train/BCN_0000012745.jpg
  inflating: bcn_20k_train/BCN_0000012746.jpg
  inflating: bcn_20k_train/BCN_0000012747.jpg
  inflating: bcn_20k_train/BCN_0000012749.jpg
  inflating: bcn_20k_train/BCN_0000012751.jpg
  inflating: bcn_20k_train/BCN_0000012752.jpg
  inflating: bcn_20k_train/BCN_0000012754.jpg
  inflating: bcn_20k_train/BCN_0000012755.jpg
  inflating: bcn_20k_train/BCN_0000012756.jpg
  inflating: bcn_20k_train/BCN_0000012757.jpg
  inflating: bcn_20k_train/BCN_0000012759.jpg
  inflating: bcn_20k_train/BCN_0000012760.jpg
  inflating: bcn_20k_train/BCN_0000012766.jpg
  inflating: bcn_20k_train/BCN_0000012767.jpg
  inflating: bcn_20k_train/BCN_0000012768.jpg
  inflating: bcn_20k_train/BCN_0000012769.jpg
  inflating: bcn_20k_train/BCN_0000012770.jpg
  inflating: bcn_20k_train/BCN_0000012771.jpg
  inflating: bcn_20k_train/BCN_0000012772.jpg
  inflating: bcn_20k_train/BCN_0000012773.jpg
  inflating: bcn_20k_train/BCN_0000012774.jpg
  inflating: bcn_20k_train/BCN_0000012776.jpg
  inflating: bcn_20k_train/BCN_0000012777.jpg
  inflating: bcn_20k_train/BCN_0000012778.jpg
  inflating: bcn_20k_train/BCN_0000012780.jpg
  inflating: bcn_20k_train/BCN_0000012782.jpg
  inflating: bcn_20k_train/BCN_0000012783.jpg
  inflating: bcn_20k_train/BCN_0000012784.jpg
  inflating: bcn_20k_train/BCN_0000012785.jpg
  inflating: bcn_20k_train/BCN_0000012787.jpg
  inflating: bcn_20k_train/BCN_0000012788.jpg
  inflating: bcn_20k_train/BCN_0000012793.jpg
  inflating: bcn_20k_train/BCN_0000012795.jpg
  inflating: bcn_20k_train/BCN_0000012796.jpg
  inflating: bcn_20k_train/BCN_0000012799.jpg
  inflating: bcn_20k_train/BCN_0000012802.jpg
  inflating: bcn_20k_train/BCN_0000012803.jpg
  inflating: bcn_20k_train/BCN_0000012805.jpg
  inflating: bcn_20k_train/BCN_0000012807.jpg
  inflating: bcn_20k_train/BCN_0000012813.jpg
  inflating: bcn_20k_train/BCN_0000012814.jpg
  inflating: bcn_20k_train/BCN_0000012815.jpg
  inflating: bcn_20k_train/BCN_0000012816.jpg
  inflating: bcn_20k_train/BCN_0000012817.jpg
  inflating: bcn_20k_train/BCN_0000012818.jpg
  inflating: bcn_20k_train/BCN_0000012820.jpg
  inflating: bcn_20k_train/BCN_0000012824.jpg
  inflating: bcn_20k_train/BCN_0000012825.jpg
  inflating: bcn_20k_train/BCN_0000012826.jpg
  inflating: bcn_20k_train/BCN_0000012828.jpg
  inflating: bcn_20k_train/BCN_0000012832.jpg
  inflating: bcn_20k_train/BCN_0000012834.jpg
  inflating: bcn_20k_train/BCN_0000012835.jpg
  inflating: bcn_20k_train/BCN_0000012837.jpg
  inflating: bcn_20k_train/BCN_0000012839.jpg
  inflating: bcn_20k_train/BCN_0000012840.jpg
  inflating: bcn_20k_train/BCN_0000012841.jpg
  inflating: bcn_20k_train/BCN_0000012845.jpg
  inflating: bcn_20k_train/BCN_0000012846.jpg
  inflating: bcn_20k_train/BCN_0000012849.jpg
  inflating: bcn_20k_train/BCN_0000012850.jpg
  inflating: bcn_20k_train/BCN_0000012851.jpg
  inflating: bcn_20k_train/BCN_0000012852.jpg
  inflating: bcn_20k_train/BCN_0000012853.jpg
  inflating: bcn_20k_train/BCN_0000012858.jpg
  inflating: bcn_20k_train/BCN_0000012860.jpg
  inflating: bcn_20k_train/BCN_0000012861.jpg
  inflating: bcn_20k_train/BCN_0000012862.jpg
  inflating: bcn_20k_train/BCN_0000012864.jpg
  inflating: bcn_20k_train/BCN_0000012865.jpg
  inflating: bcn_20k_train/BCN_0000012866.jpg
  inflating: bcn_20k_train/BCN_0000012867.jpg
  inflating: bcn_20k_train/BCN_0000012868.jpg
  inflating: bcn_20k_train/BCN_0000012869.jpg
  inflating: bcn_20k_train/BCN_0000012870.jpg
  inflating: bcn_20k_train/BCN_0000012872.jpg
  inflating: bcn_20k_train/BCN_0000012875.jpg
  inflating: bcn_20k_train/BCN_0000012878.jpg
  inflating: bcn_20k_train/BCN_0000012880.jpg
  inflating: bcn_20k_train/BCN_0000012884.jpg
  inflating: bcn_20k_train/BCN_0000012885.jpg
  inflating: bcn_20k_train/BCN_0000012888.jpg
  inflating: bcn_20k_train/BCN_0000012890.jpg
  inflating: bcn_20k_train/BCN_0000012891.jpg
  inflating: bcn_20k_train/BCN_0000012893.jpg
  inflating: bcn_20k_train/BCN_0000012894.jpg
  inflating: bcn_20k_train/BCN_0000012895.jpg
  inflating: bcn_20k_train/BCN_0000012897.jpg
  inflating: bcn_20k_train/BCN_0000012898.jpg
  inflating: bcn_20k_train/BCN_0000012899.jpg
  inflating: bcn_20k_train/BCN_0000012900.jpg
  inflating: bcn_20k_train/BCN_0000012901.jpg
  inflating: bcn_20k_train/BCN_0000012903.jpg
  inflating: bcn_20k_train/BCN_0000012905.jpg
  inflating: bcn_20k_train/BCN_0000012906.jpg
  inflating: bcn_20k_train/BCN_0000012908.jpg
  inflating: bcn_20k_train/BCN_0000012909.jpg
  inflating: bcn_20k_train/BCN_0000012911.jpg
  inflating: bcn_20k_train/BCN_0000012912.jpg
  inflating: bcn_20k_train/BCN_0000012913.jpg
  inflating: bcn_20k_train/BCN_0000012916.jpg
  inflating: bcn_20k_train/BCN_0000012918.jpg
  inflating: bcn_20k_train/BCN_0000012919.jpg
  inflating: bcn_20k_train/BCN_0000012920.jpg
  inflating: bcn_20k_train/BCN_0000012921.jpg
  inflating: bcn_20k_train/BCN_0000012924.jpg
  inflating: bcn_20k_train/BCN_0000012927.jpg
  inflating: bcn_20k_train/BCN_0000012928.jpg
  inflating: bcn_20k_train/BCN_0000012929.jpg
  inflating: bcn_20k_train/BCN_0000012932.jpg
  inflating: bcn_20k_train/BCN_0000012933.jpg
  inflating: bcn_20k_train/BCN_0000012939.jpg
  inflating: bcn_20k_train/BCN_0000012940.jpg
  inflating: bcn_20k_train/BCN_0000012941.jpg
  inflating: bcn_20k_train/BCN_0000012942.jpg
  inflating: bcn_20k_train/BCN_0000012944.jpg
  inflating: bcn_20k_train/BCN_0000012946.jpg
  inflating: bcn_20k_train/BCN_0000012948.jpg
  inflating: bcn_20k_train/BCN_0000012950.jpg
  inflating: bcn_20k_train/BCN_0000012951.jpg
  inflating: bcn_20k_train/BCN_0000012953.jpg
  inflating: bcn_20k_train/BCN_0000012954.jpg
  inflating: bcn_20k_train/BCN_0000012956.jpg
  inflating: bcn_20k_train/BCN_0000012958.jpg
  inflating: bcn_20k_train/BCN_0000012960.jpg
  inflating: bcn_20k_train/BCN_0000012961.jpg

## 2. Prepare Metadata

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from tqdm.auto import tqdm
from glob import glob

In [ ]:
data_dir = '/content'
all_images_path = glob(os.path.join(data_dir, '*', '*.jpg'))
image_id_path_dict = {os.path.splitext(os.path.basename(x))[0]: x for x in all_images_path}
lesion_type_dict = {
    'nv': 'Melanocytic nevi',
    'mel': 'Melanoma',
    'bkl': 'Benign keratosis-like lesions',
    'bcc': 'Basal cell carcinoma',
    'akiec': 'Actinic keratoses',
    'vasc': 'Vascular lesions',
    'df': 'Dermatofibroma'
}

### 2.1 display HAM10000 metadata

In [ ]:
 HAM_df = pd.read_csv(os.path.join(data_dir, 'HAM10000_metadata.csv'))
 HAM_df.head()

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

In [ ]:
HAM_df['path'] = HAM_df['image_id'].map(image_id_path_dict.get)
HAM_df.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,path
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0027419.jpg
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0025030.jpg
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0026769.jpg
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0025661.jpg
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,/content/ham10000_images_part_2/ISIC_0031633.jpg

In [ ]:
HAM_df['dx'].value_counts()

dx
nv       6705
mel      1113
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: count, dtype: int64

### 2.2 display BCN20000 metadata

In [ ]:
BCN_df = pd.read_csv('/content/drive/MyDrive/All_BCN20000/bcn_20k_train.csv')

BCN_dir = os.path.join(data_dir, 'bcn_20k_train')

def check_path_exist(filename):

  fullpath = os.path.join(BCN_dir, filename)

  if os.path.exists(fullpath):
    return fullpath
  else:
    return np.nan

BCN_df['path'] = BCN_df['bcn_filename'].apply(lambda x: os.path.join(BCN_dir, x))
BCN_df.head()

,bcn_filename,age_approx,anatom_site_general,diagnosis,lesion_id,capture_date,sex,split,path
0,BCN_0000000001.jpg,55.0,anterior torso,MEL,BCN_0003884,2012-05-16,male,train,/content/bcn_20k_train/BCN_0000000001.jpg
1,BCN_0000000003.jpg,50.0,anterior torso,MEL,BCN_0000019,2015-07-09,female,train,/content/bcn_20k_train/BCN_0000000003.jpg
2,BCN_0000000004.jpg,85.0,head/neck,SCC,BCN_0003499,2015-11-23,male,train,/content/bcn_20k_train/BCN_0000000004.jpg
3,BCN_0000000006.jpg,60.0,anterior torso,NV,BCN_0003316,2015-06-16,male,train,/content/bcn_20k_train/BCN_0000000006.jpg
4,BCN_0000000010.jpg,30.0,anterior torso,BCC,BCN_0004874,2014-02-18,female,train,/content/bcn_20k_train/BCN_0000000010.jpg

### 2.3 Turn BCN to HAM format

In [ ]:
map_BCN_to_HAM = {
    'NV': 'nv',
    'MEL': 'mel',
    'BKL': 'bkl',
    'BCC': 'bcc',
    'AK': 'akiec',
    'VASC': 'vasc',
    'DF': 'df'
}

BCN_df['dx'] = BCN_df['diagnosis'].map(map_BCN_to_HAM)
BCN_df = BCN_df.dropna()
BCN_df['dx'].value_counts()

dx
nv       4122
mel      2832
bcc      2747
bkl      1109
akiec     716
df        121
vasc      111
Name: count, dtype: int64

In [ ]:
BCN_df = BCN_df.rename(columns={
    'age_approx' : 'age',
    'anatom_site_general' : 'location',
    })

BCN_df.head(5)

,bcn_filename,age,location,diagnosis,lesion_id,capture_date,sex,split,path,dx
0,BCN_0000000001.jpg,55.0,anterior torso,MEL,BCN_0003884,2012-05-16,male,train,/content/bcn_20k_train/BCN_0000000001.jpg,mel
1,BCN_0000000003.jpg,50.0,anterior torso,MEL,BCN_0000019,2015-07-09,female,train,/content/bcn_20k_train/BCN_0000000003.jpg,mel
3,BCN_0000000006.jpg,60.0,anterior torso,NV,BCN_0003316,2015-06-16,male,train,/content/bcn_20k_train/BCN_0000000006.jpg,nv
4,BCN_0000000010.jpg,30.0,anterior torso,BCC,BCN_0004874,2014-02-18,female,train,/content/bcn_20k_train/BCN_0000000010.jpg,bcc
5,BCN_0000000011.jpg,20.0,anterior torso,NV,BCN_0004756,2015-03-19,female,train,/content/bcn_20k_train/BCN_0000000011.jpg,nv

In [ ]:
map_df = pd.DataFrame({
    #'lesion_id' : BCN_df['lesion_id'],
    'age' : BCN_df['age'],
    'location' : BCN_df['location'],
    'sex' : BCN_df['sex'],
    'dx' : BCN_df['dx'],
    'path' : BCN_df['path'],
    'image_id' : BCN_df['bcn_filename'],
})

In [ ]:
map_df.head()

,age,location,sex,dx,path,image_id
0,55.0,anterior torso,male,mel,/content/bcn_20k_train/BCN_0000000001.jpg,BCN_0000000001.jpg
1,50.0,anterior torso,female,mel,/content/bcn_20k_train/BCN_0000000003.jpg,BCN_0000000003.jpg
3,60.0,anterior torso,male,nv,/content/bcn_20k_train/BCN_0000000006.jpg,BCN_0000000006.jpg
4,30.0,anterior torso,female,bcc,/content/bcn_20k_train/BCN_0000000010.jpg,BCN_0000000010.jpg
5,20.0,anterior torso,female,nv,/content/bcn_20k_train/BCN_0000000011.jpg,BCN_0000000011.jpg

In [ ]:
df_all = pd.concat([HAM_df, map_df], ignore_index=True)

df_all['dx'].value_counts()

dx
nv       10827
mel       3945
bcc       3261
bkl       2208
akiec     1043
vasc       253
df         236
Name: count, dtype: int64

### 2.4 Deal with Duplicated Data

In [ ]:
df_all.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,path,location
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0027419.jpg,NaN
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0025030.jpg,NaN
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0026769.jpg,NaN
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0025661.jpg,NaN
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,/content/ham10000_images_part_2/ISIC_0031633.jpg,NaN

In [ ]:
lesion_count = df_all['lesion_id'].value_counts() # value_counts ignore NaN

HAM_is_unique = df_all['lesion_id'].map(lesion_count) == 1

BCN_data = df_all['lesion_id'].isna()

df_undup = df_all[HAM_is_unique | BCN_data].copy()

df_undup['dx'].value_counts()

dx
nv       8537
mel      3062
bcc      2922
bkl      1549
akiec     867
vasc      175
df        160
Name: count, dtype: int64

### 2.5 Drop some classes
#### For the purpose of get rid of unbalancing class problem.

In [ ]:
df_undup = df_undup[~df_undup['dx'].isin(['akiec', 'vasc', 'df'])]
df_undup['dx'].value_counts()

dx
nv     8537
mel    3062
bcc    2922
bkl    1549
Name: count, dtype: int64

### 2.6 Indexing

In [ ]:
indexing_map = {
    'nv': 0,
    'mel': 1,
    'bkl': 2,
    'bcc': 3,
}

df_undup['cell_type_idx'] = df_undup['dx'].map(indexing_map)
df_undup['cell_type_idx'].value_counts()

cell_type_idx
0    8537
1    3062
3    2922
2    1549
Name: count, dtype: int64

###2.7 Spliting Data 80:20

In [ ]:
from sklearn.model_selection import train_test_split

y = df_undup['cell_type_idx']
_, df_val = train_test_split(df_undup,test_size=0.2, random_state = 101, stratify = y)

In [ ]:
# This set will be df_original excluding all rows that are in the val set
# This function identifies if an image is part of the train or val set
def get_val_rows(x):
  #create a list of all the lension_id's in the val set
  val_list = list(df_val['lesion_id'])
  if str(x) in val_list:
    return 'val'
  else:
    return 'train'

#identify train and val rows
#create a new column that is a copy of the image_id column
df_undup['train_or_val'] = df_undup['lesion_id']

#apply function to this new column
df_undup['train_or_val'] = df_undup['train_or_val'].apply(get_val_rows)

df_train = df_undup[df_undup['train_or_val'] == 'train']

In [ ]:
print("Training DATASET")
print(df_train['dx'].value_counts())
print("===========================")
print("Testing DATASET")
print(df_val['dx'].value_counts())

Training DATASET
dx
nv     7667
mel    3000
bcc    2884
bkl    1475
Name: count, dtype: int64
===========================
Testing DATASET
dx
nv     1708
mel     612
bcc     584
bkl     310
Name: count, dtype: int64

### 2.7 Balance each class in Training DATASET

In [ ]:
df_train['duplicates'] = 'unduplicated'

/tmp/ipython-input-4194865416.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['duplicates'] = 'unduplicated'

In [ ]:
def duplicate(df: pd.DataFrame, target_class: list[str], max_per_class: int):
  augmented_df = df.copy()

  for i in tqdm(target_class, desc='BALANCING THE CLASS', unit = 'image'):

    class_subset = df[(df['cell_type_idx'] == i) & (df['duplicates'] == 'unduplicated')]
    if class_subset.empty:
                print(f"Warning: No unduplicated rows for class {i}. Skipping.")
                continue

    current_count = (augmented_df['cell_type_idx'] == i).sum()
    new_row = []

    while current_count< max_per_class:
      random_row = class_subset.sample(n=1).iloc[0]

      row_dict = random_row.to_dict()
      row_dict['duplicates'] = 'duplicated'
      new_row.append(row_dict)
      current_count += 1

    if new_row:
      augmented_df = pd.concat([augmented_df, pd.DataFrame(new_row)], ignore_index=True)

  return augmented_df

In [ ]:
df_train.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,path,location,cell_type_idx,train_or_val,duplicates
15,HAM_0007207,ISIC_0031326,bkl,histo,65.0,male,back,/content/ham10000_images_part_2/ISIC_0031326.jpg,NaN,2,train,unduplicated
33,HAM_0005612,ISIC_0024981,bkl,histo,80.0,male,scalp,/content/HAM10000_images_part_1/ISIC_0024981.jpg,NaN,2,train,unduplicated
34,HAM_0005388,ISIC_0027815,bkl,histo,80.0,male,chest,/content/HAM10000_images_part_1/ISIC_0027815.jpg,NaN,2,train,unduplicated
50,HAM_0003670,ISIC_0030105,bkl,histo,80.0,female,unknown,/content/ham10000_images_part_2/ISIC_0030105.jpg,NaN,2,train,unduplicated
55,HAM_0001983,ISIC_0030377,bkl,histo,70.0,male,back,/content/ham10000_images_part_2/ISIC_0030377.jpg,NaN,2,train,unduplicated

In [ ]:
max_balance_num = max(df_train['dx'].value_counts().tolist())

target_class = [1,2,3,4]

balance_df_train = duplicate(df_train, target_class, max_balance_num)

balance_df_train['dx'].value_counts()

BALANCING THE CLASS:   0%|          | 0/4 [00:00<?, ?image/s]

Warning: No unduplicated rows for class 4. Skipping.

dx
bkl    7667
nv     7667
mel    7667
bcc    7667
Name: count, dtype: int64

## Training

### 3.1 Create Dataloader

In [ ]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)

In [ ]:
import torch
from torch.utils.data import Dataset
from PIL import Image
# Create our class of PyTorch dataloader
class SkinDataLoader(Dataset):
  def __init__(self, df, transforms=None):
    # NOTE: df = pandas Dataframe or list that containing a filepaths and labels
    # transform = torchvision.transforms (or your own func) to apply to each sample
    self.df = df
    self.transform = transforms

  def __len__(self):
    #Return number of samples
    return len(self.df)

  def __getitem__(self, index):
    X = Image.open(self.df["path"][index])
    y = torch.tensor(int(self.df['cell_type_idx'][index]))

    if self.transform:
      X = self.transform(X)
    return X, y

### 3.2 Create Transformer

In [ ]:
from torch.utils.data import DataLoader
from torchvision import transforms
BATCH_SIZE = 10

train_tfms = transforms.Compose([
    #transforms.Resize((224,224)),
    transforms.Resize((512,512)),
    transforms.RandomRotation(degrees=30),
    transforms.RandomHorizontalFlip(p=0.25),
    transforms.RandomVerticalFlip(p=0.25),
    transforms.ColorJitter(brightness=0.1, contrast=0.1, hue=0.1),
    transforms.ToTensor()
])

training_set = SkinDataLoader(df_train, transforms = train_tfms)
train_dataloader = DataLoader(training_set, batch_size = BATCH_SIZE , shuffle = True, num_workers=4)

validation_set = SkinDataLoader(df_val, transforms = train_tfms)
val_dataloader = DataLoader(validation_set, batch_size= BATCH_SIZE, shuffle = True, num_workers=4)

train_dataloader, val_dataloader

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:627: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(

(<torch.utils.data.dataloader.DataLoader at 0x7b99dee70440>,
 <torch.utils.data.dataloader.DataLoader at 0x7b99dee70530>)

### 3.3 Create DenseNet Architecture (DenseNet121)

In [ ]:
# feature_extract is a boolean that defines if we are finetuning or feature extracting.
# If feature_extract = False, the model is finetuned and all model parameters are updated.
# If feature_extract = True, only the last layer parameters are updated, the others remain fixed.
def set_parameter_requires_grad(model, feature_extracting):
    if feature_extracting:
        for param in model.parameters():
            param.requires_grad = False

In [ ]:
import torch
from torch import nn
import torchvision
from torchvision import models

def Densenet121(num_classes, feature_extract, use_pretrained=True):
  # Densenet121
  model_ft = models.densenet121(pretrained=use_pretrained)
  set_parameter_requires_grad(model_ft, feature_extract)
  num_ftrs = model_ft.classifier.in_features
  model_ft.classifier = nn.Linear(num_ftrs, num_classes)
  #input_size = 224
  input_size = 450

  return model_ft, input_size

### 3.4 Create instance of denseNet

In [ ]:
if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'
print(device)

cpu

In [ ]:
model_0, input_size = Densenet121(
                                  num_classes = df_train['dx'].nunique(),
                                  feature_extract = False,
                                  use_pretrained=True
)

model_0.to(device)

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to /root/.cache/torch/hub/checkpoints/densenet121-a639ec97.pth

100%|██████████| 30.8M/30.8M [00:00<00:00, 98.7MB/s]

DenseNet(
  (features): Sequential(
    (conv0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (norm0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace=True)
    (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(96, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer3): _DenseLayer(
        (norm1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer4): _DenseLayer(
        (norm1): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(160, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer5): _DenseLayer(
        (norm1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer6): _DenseLayer(
        (norm1): BatchNorm2d(224, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(224, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
    )
    (transition1): _Transition(
      (norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (pool): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
    (denseblock2): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(160, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer3): _DenseLayer(
        (norm1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer4): _DenseLayer(
        (norm1): BatchNorm2d(224, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(224, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer5): _DenseLayer(
        (norm1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer6): _DenseLayer(
        (norm1): BatchNorm2d(288, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(288, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer7): _DenseLayer(
        (norm1): BatchNorm2d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(320, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer8): _DenseLayer(
        (norm1): BatchNorm2d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(352, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer9): _DenseLayer(
        (norm1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(384, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer10): _DenseLayer(
        (norm1): BatchNorm2d(416, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(416, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer11): _DenseLayer(
        (norm1): BatchNorm2d(448, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(448, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer12): _DenseLayer(
        (norm1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(480, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
    )
    (transition2): _Transition(
      (norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (pool): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
    (denseblock3): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(288, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(288, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer3): _DenseLayer(
        (norm1): BatchNorm2d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(320, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer4): _DenseLayer(
        (norm1): BatchNorm2d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(352, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer5): _DenseLayer(
        (norm1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(384, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer6): _DenseLayer(
        (norm1): BatchNorm2d(416, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(416, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer7): _DenseLayer(
        (norm1): BatchNorm2d(448, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(448, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer8): _DenseLayer(
        (norm1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(480, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer9): _DenseLayer(
        (norm1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer10): _DenseLayer(
        (norm1): BatchNorm2d(544, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(544, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer11): _DenseLayer(
        (norm1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer12): _DenseLayer(
        (norm1): BatchNorm2d(608, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(608, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer13): _DenseLayer(
        (norm1): BatchNorm2d(640, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(640, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer14): _DenseLayer(
        (norm1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(672, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer15): _DenseLayer(
        (norm1): BatchNorm2d(704, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(704, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer16): _DenseLayer(
        (norm1): BatchNorm2d(736, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(736, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer17): _DenseLayer(
        (norm1): BatchNorm2d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(768, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer18): _DenseLayer(
        (norm1): BatchNorm2d(800, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(800, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer19): _DenseLayer(
        (norm1): BatchNorm2d(832, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(832, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer20): _DenseLayer(
        (norm1): BatchNorm2d(864, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(864, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer21): _DenseLayer(
        (norm1): BatchNorm2d(896, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(896, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)

### 3.5 Define Training and Validation steps

In [ ]:
!pip install torchmetrics -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 18.7 MB/s eta 0:00:00

In [ ]:
# this function is used during training process, to calculation the loss and accuracy
class AverageMeter(object):
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

In [ ]:
total_loss_train, total_acc_train = [],[]
def train(train_loader, model, criterion, optimizer, epoch):
    model.train()
    train_loss = AverageMeter()
    train_acc = AverageMeter()
    curr_iter = (epoch - 1) * len(train_loader)
    for i, data in enumerate(train_loader):
        images, labels = data
        N = images.size(0)
        # print('image shape:',images.size(0), 'label shape',labels.size(0))
        images = Variable(images).to(device)
        labels = Variable(labels).to(device)

        optimizer.zero_grad()
        outputs = model(images)

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        prediction = outputs.max(1, keepdim=True)[1]
        train_acc.update(prediction.eq(labels.view_as(prediction)).sum().item()/N)
        train_loss.update(loss.item())
        curr_iter += 1
        if (i + 1) % 100 == 0:
            print('[epoch %d], [iter %d / %d], [train loss %.5f], [train acc %.5f]' % (
                epoch, i + 1, len(train_loader), train_loss.avg, train_acc.avg))
            total_loss_train.append(train_loss.avg)
            total_acc_train.append(train_acc.avg)
    return train_loss.avg, train_acc.avg

In [ ]:
from torch.autograd import Variable
def validate(val_loader, model, criterion, optimizer, epoch):

    # Insert this at the top of validate(), before model.eval()
    unique_labels = set()
    for _, labels in val_loader:
        unique_labels.update(labels.tolist())
    print("VAL labels:", sorted(unique_labels))

    model.eval()
    val_loss = AverageMeter()
    val_acc = AverageMeter()
    with torch.no_grad():
        for i, data in enumerate(val_loader):
            images, labels = data
            N = images.size(0)
            images = Variable(images).to(device)
            labels = Variable(labels).to(device)

            outputs = model(images)
            prediction = outputs.max(1, keepdim=True)[1]

            val_acc.update(prediction.eq(labels.view_as(prediction)).sum().item()/N)

            val_loss.update(criterion(outputs, labels).item())

    print('------------------------------------------------------------')
    print('[epoch %d], [val loss %.5f], [val acc %.5f]' % (epoch, val_loss.avg, val_acc.avg))
    print('------------------------------------------------------------')
    return val_loss.avg, val_acc.avg

### 3.6 Define Loss Function and Optimizer

In [ ]:
from torch import optim

loss_fn = nn.CrossEntropyLoss().to(device)
optimizer = optim.Adam(model_0.parameters(), lr= 1e-3)

### 3.7 Training Model

In [ ]:
torch.manual_seed(101)

epoch_num = 5
best_val_acc = 0
total_loss_val, total_acc_val = [],[]
for epoch in tqdm(range(1, epoch_num+1)):

    loss_train, acc_train = train(train_dataloader, model_0, loss_fn, optimizer, epoch)
    loss_val, acc_val = validate(val_dataloader, model_0, loss_fn, optimizer, epoch)
    total_loss_val.append(loss_val)
    total_acc_val.append(acc_val)
    if acc_val > best_val_acc:
        best_val_acc = acc_val
        print('*****************************************************')
        print('best record: [epoch %d], [val loss %.5f], [val acc %.5f]' % (epoch, loss_val, acc_val))
        print('*****************************************************')

  0%|          | 0/5 [00:00<?, ?it/s]

[epoch 1], [iter 100 / 1503], [train loss 1.16246], [train acc 0.53300]
[epoch 1], [iter 200 / 1503], [train loss 1.11769], [train acc 0.54700]
[epoch 1], [iter 300 / 1503], [train loss 1.08905], [train acc 0.55633]
[epoch 1], [iter 400 / 1503], [train loss 1.06585], [train acc 0.56850]
[epoch 1], [iter 500 / 1503], [train loss 1.05217], [train acc 0.57560]